# Generated by Django 3.2.15 on 2022-08-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=20, verbose_name='Nickname')),
                ('password', models.CharField(max_length=24, verbose_name='Password')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
            ],
        ),
    ]
